# Generated by Django 2.2.4 on 2019-09-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='频道')),
                ('bianmaqi', models.CharField(blank=True, max_length=50, null=True, verbose_name='编码器')),
                ('jieru', models.CharField(blank=True, max_length=50, null=True, verbose_name='sdi/ip')),
                ('type', models.CharField(max_length=50, verbose_name='类型')),
                ('pindao_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='频道ID')),
                ('beizhu', models.CharField(blank=True, max_length=50, null=True, verbose_name='beizhu')),
            ],
            options={
                'verbose_name': '所有频道',
                'verbose_name_plural': '所有频道',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Jiaoyu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='频道')),
                ('bianmaqi', models.CharField(blank=True, max_length=50, null=True, verbose_name='编码器')),
                ('jieru', models.CharField(blank=True, max_length=50, null=True, verbose_name='sdi/ip')),
                ('pindao_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='频道ID')),
                ('beizhu', models.CharField(blank=True, max_length=50, null=True, verbose_name='beizhu')),
            ],
            options={
                'verbose_name': '教育频道',
                'verbose_name_plural': '教育频道',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='频道')),
                ('bianmaqi', models.CharField(blank=True, max_length=50, null=True, verbose_name='编码器')),
                ('jieru', models.CharField(blank=True, max_length=50, null=True, verbose_name='sdi/ip')),
                ('pindao_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='频道ID')),
                ('beizhu', models.CharField(blank=True, max_length=50, null=True, verbose_name='beizhu')),
            ],
            options={
                'verbose_name': '其它频道',
                'verbose_name_plural': '其它频道',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='源站地址')),
                ('jifang', models.CharField(max_length=50, verbose_name='所在机房')),
                ('type', models.CharField(max_length=50, verbose_name='源站服务类型')),
                ('jiankong', models.CharField(max_length=50, verbose_name='后台监控地址')),
            ],
            options={
                'verbose_name': '源站信息',
                'verbose_name_plural': '源站信息',
            },
        ),
        migrations.CreateModel(
            name='Weishi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='频道')),
                ('bianmaqi', models.CharField(blank=True, max_length=50, null=True, verbose_name='编码器')),
                ('jieru', models.CharField(blank=True, max_length=50, null=True, verbose_name='sdi/ip')),
                ('pindao_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='频道ID')),
                ('beizhu', models.CharField(blank=True, max_length=50, null=True, verbose_name='beizhu')),
            ],
            options={
                'verbose_name': '地方卫视频道',
                'verbose_name_plural': '地方卫视频道',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Yangshi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='频道')),
                ('bianmaqi', models.CharField(blank=True, max_length=50, null=True, verbose_name='编码器')),
                ('jieru', models.CharField(blank=True, max_length=50, null=True, verbose_name='sdi/ip')),
                ('pindao_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='频道ID')),
                ('beizhu', models.CharField(blank=True, max_length=50, null=True, verbose_name='beizhu')),
            ],
            options={
                'verbose_name': '央视频道',
                'verbose_name_plural': '央视频道',
                'ordering': ['name'],
            },
        ),
    ]
